# base image
FROM cypress/browsers:chrome67-ff57

# set working directory
WORKDIR /app

# install cypress
RUN npm install cypress

COPY cypress/* cypress/
COPY package*.json ./
COPY cypress.json ./

ENV CYPRESS_URL=client
ENV CYPRESS_PORT=80